### PR TITLE
Add in more parameters to store

### LINKED ISSUE #16: Expose --used and --executed for store tool

### PR DESCRIPTION
**Pull request by thomasyu888**
fixes #16

### CODE REVIEW

**Review by wpoehlm — APPROVED** [review]
Looks good to me, a couple optional ideas:

- Could we add Activity to this?
- Should we make a separate tool that takes an array of files? That way you can build a single synapse store step into a workflow that has many outputs

**Comment by thomasyu888** [comment]
Thanks @wpoehlm. The `synapse store` function doesn't have the concept of an "activity"

```
synapse store -h
usage: synapse store [-h] (--parentid syn123 | --id syn123 | --type TYPE)
                     [--name NAME]
                     [--description DESCRIPTION | --descriptionFile DESCRIPTION_FILE_PATH]
                     [--used [target [target ...]]]
                     [--executed [target [target ...]]] [--limitSearch projId]
                     [--noForceVersion] [--annotations ANNOTATIONS]
                     [--replace]
                     [FILE]

positional arguments:
  FILE                  file to be added to synapse.

optional arguments:
  -h, --help            show this help message and exit
  --parentid syn123, --parentId syn123, -parentid syn123, -parentId syn123
                        Synapse ID of project or folder where to upload data
                        (must be specified if --id is not used.
  --id syn123           Optional Id of entity in Synapse to be updated.
  --type TYPE           Type of object, such as "File", "Folder", or
                        "Project", to create in Synapse. Defaults to "File"
  --name NAME, -name NAME
                        Name of data object in Synapse
  --description DESCRIPTION, -description DESCRIPTION
                        Description of data object in Synapse.
  --descriptionFile DESCRIPTION_FILE_PATH, -descriptionFile DESCRIPTION_FILE_PATH
                        Path to a markdown file containing description of
                        project/folder
  --used [target [target ...]], -used [target [target ...]]
                        Synapse ID, a url, or a local file path (of a file
                        previouslyuploaded to Synapse) from which the
                        specified entity is derived
  --executed [target [target ...]], -executed [target [target ...]]
                        Synapse ID, a url, or a local file path (of a file
                        previouslyuploaded to Synapse) that was executed to
                        generate the specified entity
  --limitSearch projId  Synapse ID of a container such as project or folder to
                        limit search for provenance files.
  --noForceVersion      Do not force a new version to be created if the
                        contents of the file have not changed. The default is
                        a new version is created.
  --annotations ANNOTATIONS
                        Annotations to add as a JSON formatted string, should
                        evaluate to a dictionary (key/value pairs). Example:
                        '{"foo": 1, "bar":"quux"}'
  --replace             Replace all existing annotations with the given
                        annotations
```

It builds the `Activity` for you within the `store` function.  As for the separate tool, we most certainly could, that tool would probably be a workflow that scattered across an array input to call the store CWL tool.  (Not sure if that would belong in this repo)

**Comment by thomasyu888** [comment]
There is a `synapse set-provenance` which I could add as a tool

**Comment by wpoehlm** [comment]
> 
> 
> There is a `synapse set-provenance` which I could add as a tool

That could be a useful tool, although if the store function builds the activity for us then it probably isn't necessary for workflows? 

> a workflow that s

There definitely lots of situations where a single input file produces an array of output files. Scattering over the array of inputs to pass into the store tool sounds reasonable

**Pull request merged**
